/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'manabehideyuki' at '17/06/25 17:28' with Gradle 3.0
 *
 * @author manabehideyuki, @date 17/06/25 17:28
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
